build:
  version: "1.0"

accounts:
  message: "Welcome to EasyBank DOES THIS CHANGE related APIs"
  contactDetails:
    name: "John doe"
    email: "john@mailme.com"
  onCallSupport:
    - 123-456-7890
    - 123-456-7811
